"""test-PY

Revision ID: 5dbfb896525d
Revises: fcafcd204069
Create Date: 2023-06-06 21:53:31.090531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbfb896525d'
down_revision = 'fcafcd204069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'genre_id')
    # ### end Alembic commands ###
