"""test ex

Revision ID: dd23f48ec4db
Create Date: 2023-06-06 20:39:33.254630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd23f48ec4db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('surname', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('secname', sa.String(), nullable=False),
        sa.Column('date_of_birth', sa.String(), nullable=False),
        sa.Column('date_of_death', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('numer', sa.Integer(), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name_genre', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
