"""test

Revision ID: fcafcd204069
Revises: dd23f48ec4db
Create Date: 2023-06-06 21:51:01.828368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcafcd204069'
down_revision = 'dd23f48ec4db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('books_id', sa.Integer(), nullable=True))
    op.add_column('authors', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authors', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'authors', 'books', ['books_id'], ['id'])
    op.add_column('books', sa.Column('authors_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'authors', ['authors_id'], ['id'])
    op.add_column('genre', sa.Column('authors_id', sa.Integer(), nullable=True))
    op.add_column('genre', sa.Column('books_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'genre', 'authors', ['authors_id'], ['id'])
    op.create_foreign_key(None, 'genre', 'books', ['books_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='foreignkey')
    op.drop_constraint(None, 'genre', type_='foreignkey')
    op.drop_column('genre', 'books_id')
    op.drop_column('genre', 'authors_id')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'authors_id')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'genre_id')
    op.drop_column('authors', 'books_id')
    # ### end Alembic commands ###
